version: '3.6'
services:
  nestor:
    build:
      context: .
    container_name: composed_bot
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
  database:
    image: mongo
    container_name: bot_mongo
    environment:
      - MONGO_INITDB_DATABASE=bot
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017-27019:27017-27019'
volumes:
  mongodb: