version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # Standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - network
    container_name: rabbitmq
    restart: 'always'

  nestor_wikipedia_search:
    build:
      context: ./nestor_wikipedia_search
    container_name: nestor_wikipedia_search
    networks:
      - network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    restart: 'always'
  nestor_slack_reader_2:
    build:
      context: ./nestor_slack_reader_2
    container_name: nestor_slack_reader_2
    ports:
      - '3000:3000'
    networks:
      - network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
  nestor_slack_writer:
    build:
      context: ./nestor_slack_writer
    container_name: nestor_slack_writer
    networks:
      - network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
networks:
  network: {}