version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # Standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - network
    container_name: rabbitmq
    restart: 'always'

  consumer:
    build:
      context: ./consumer
    container_name: nestor_consumer
    networks:
      - network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
  publisher:
    build:
      context: ./publisher
    container_name: nestor_publisher
    networks:
      - network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
networks:
  network: {}